system:
  traces: /data/pengmiao/ML-DPC-S0/LoadTraces 
  processed: processed 
  model: model
  res: res

train:
  epochs: 50 
  lr: 0.0002
  gamma: 0.1
  step-size: 20
  early-stop: 5 

kd:
  alpha: 0.1 
  temperature: 2 

threshold:
  samples: 1000

amm:
  n_samples_train: -1
  n_samples_test: -1

trace-data:
  train: 8 
  total: 10 
  skip: 1 
  batch-size: 256

model:
  mix:
    dim: 16
    depth: 3
    channel_dim: 32
  ms:
    input_size: 100
    hidden_size: 16 
    num_classes: 256
  mt:
    input_size: 100
    hidden_size: 1024 
    num_classes: 256
  rs:
    channels: 1
    dim: 4
  rt:
    channels: 1
    dim: 64
  vit:
    dim: 16
    depth: 2
    heads: 2
    mlp_dim: 16
    channels: 1

simulator:
  degree: 16

hardware:
  block-bits: 6
  total-bits: 64
  look-back: 9
  pred-forward: 128
  page-bits: 12
  delta-bound: 128
  split-bits: 6
  filter-size: 16
  bitmap-size: 256 # 2 * delta-bound
  block-num-bits: 58 # total-bits - block-bits
